### ISSUE TITLE
Decide on front-end tech stack

### ISSUE THREAD

**Issue by onatbas** [SWE574-Unity/Heritage#10]
We might as well discuss which technologies to use in front-end, browser facing interface.

Since it is decided to use Ionic in conjunction with angular, I propose using that code base for front-end as well. As long as we can make the layout more suited for browser and It doesn't look like a zoomed version of the mobile, we'll be fine. @bozavci has some experience on this. 

Any other tech stack proposal ?

**Comment by bozavci** [comment]
This is unusual but i cant see why not. We should be able to maintain a single page ionic app with css and media queries. There is an existing discussion on ionic forum https://forum.ionicframework.com/t/deploy-ionic-app-as-a-website/2845 . There is not an agreement on this topic while some says its applicable , others say it is not a good practice. 

Also in this scenario we need to consider web app restrictions in mobile development.

**Comment by bozavci** [comment]
This is unusual but i cant see why not. We should be able to maintain a single page ionic app with css and media queries. There is an existing discussion on ionic forum https://forum.ionicframework.com/t/deploy-ionic-app-as-a-website/2845 . There is not an agreement on this topic while some says its applicable , others say it is not a good practice. 

Also in this scenario we need to consider web app restrictions in mobile development.

**Comment by bozavci** [comment]
It turns out with Ionic 1.2 there is offical support for this http://www.nikola-breznjak.com/blog/javascript/ionic/ionic-1-2-is-out/?utm_content=buffer5f770&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by onatbas** [comment]
That is fantastic! If the team decides on doing that, this will mean adding another deployment for the CI/CD pipeline. 

I think this is great. A complete seperate view layer, and it works with same code for mobile.

**Comment by NurErtem** [comment]
well, i have raised this question 2 times in class. My understnading is that there might be req for a native android app. after the req elicitation we can be more clear about the direction.

**Comment by bozavci** [comment]
Well normally I agree with you 100% that this type of decision should be made after requirements elicitation is finished. However in this case ionic is technically capable of handling almost anything that android is capable of and again "technically" we can create the same experience with ionic for desktop web application with the help of HTML5 and CSS3. If there is not a non-functional requirement that dictates android, we would not have a problem fulfilling any function requirements. I think we can leave this decision to Monday and share this idea with our product owner and then make the final decision.

**Comment by onatbas** [comment]
I added a requirement proposal explaining my understanding of what is the expectation is gonna be from an andriod app, I'd really appreciate any feedback from you, as there's an ongoing discussion about an android app here.

https://github.com/SWE574-TeamUnity/RepoUnity/issues/8#issuecomment-281069780
