### ISSUE TITLE
CI/CD pipeline

### ISSUE THREAD

**Issue by onatbas** [SWE574-Unity/Heritage#11]
I want to discuss CI/CD for integration.

If we're gonna do it, there are three things to deploy:
- [ ] Backend
- [ ] Mobile
- [ ] Frontend (If we use a seperate view layer, see [#10](https://github.com/SWE574-TeamUnity/RepoUnity/issues/10) )

First thing to discuss is CI service. Travis vs. Jenkins ? 

Here are my marks.

| Jenkins | Travis |
| ------ | ------ |
| Requires host | Self-host ✔|
| We maintain it | Self-maintained ✔|
| Familiar ✔| Not as familiar |
| Private repo ✔| Public only |
| Indirect costs | Free for public ✔|
| Integration via Git | Direct integration with GitHub ✔|
| deployment script host on Jenkins | deployment script host in Repository ✔|

In light of that, I say let's try Travis. It's also very easy to learn and write jobs. It's simply a linux machine.

---

For mobile, I think a solution like HockeyApp (free up to 2 mobile apps) would be great. With a simple curl request, we can send our apks directly into a private app market from which we can download our apps. CD for mobile, who doesn't want that? 

We can also look into HockeyApp's cordova plugin for crash reports, updates etc. but that might be too much to decide now. 

What do you think @SWE574-TeamUnity/unity ?

**Comment by bozavci** [comment]
My previous experience is with Jenkins but I would love to learn Travis therefore I vote Travis.

**Comment by onatbas** [comment]
Updated the list and added front-end, there's possiblity off having a seperate deployment for front-end. (See [#10](https://github.com/SWE574-TeamUnity/RepoUnity/issues/10)  )

**Comment by edipcilli** [comment]
This week i started to work in siemens, we are using jenkins here but i would like to learn Travis too. so both of them are ok for me.

**Comment by koray-bostanci** [comment]
Travis is the best option in my opinion because there is no setup time and fee. All we have to do is maintain a configuration file. Easy Github integration is also an advantage.

So, I vote for Travis for our project.

**Comment by koray-bostanci** [comment]
Closing the issue as **_Travis_**, please re-open if you want to add something.
