### ISSUE TITLE
Milestones should be created

### ISSUE THREAD

**Issue by ozanyarci** [SWE574-Unity/Heritage#13]
Milestones should be created for this project. Milestones are the key points in the project. Or as the wikipedia says : Milestones are tools used in project management to mark specific points along a project timeline. 

Some suggestions:

1. Requirements done
2. Mockups done
3. Backend is initialized
4. Mobile frontend is initialized
5. Web frontend is initialized
6. Research done.
7. Design document is done.

Any other suggestions or modifications will be appreciated.

**Comment by bozavci** [comment]
I was also feeling that something was missing :) we definitely need milestones but maybe we can set milestones weekly and assign issues to milestones ?

**Comment by NurErtem** [comment]
i agree with the suggestions. i guess ozan did not list them as from first to last. maybe we can decide on the list order to with some additional items:

Research done.
Requirements done
Design document is done.
Mockups done
Backend is initialized
Firefox addon development
Mobile frontend is initialized
Web frontend is initialized
Testing 
Deployment and Production to AWS

**Comment by koray-bostanci** [comment]
Since it's mentioned by the instructor in piazza on previous Monday, planning the milestones is a high-priority issue I think.

![image](https://cloud.githubusercontent.com/assets/8762343/24453717/b66ecf68-1491-11e7-859b-e37e3e853ee9.png)
