### ISSUE TITLE
Mock-ups needs to be created based on requirements elicitations.

### ISSUE THREAD

**Issue by bozavci** [SWE574-Unity/Heritage#15]

**Comment by eylulakar** [comment]
Some mockup screens containing the following pages:

Sign in & Register
Settings
Latest Posts/Pot List
Create Content
Content Detail
Content Detail with Annotations
Create Annotation
Annotations List(of a user)

https://eylulakar574.mybalsamiq.com/projects/swe574/grid

**Comment by bozavci** [comment]
These are some sketches I made. I know it looks bad but it can help with clarifying the requirements. 
![photo 26-02-2017 15 36 04](https://cloud.githubusercontent.com/assets/22366324/23339815/ecf7856a-fc32-11e6-80e5-5d3f7a8cbb5d.jpg)
![photo 26-02-2017 15 36 12](https://cloud.githubusercontent.com/assets/22366324/23339816/ecf8bb9c-fc32-11e6-8d59-4419425082b5.jpg)
![photo 26-02-2017 15 36 19](https://cloud.githubusercontent.com/assets/22366324/23339817/ecf9cadc-fc32-11e6-875b-01eea4401548.jpg)
![photo 26-02-2017 15 36 26](https://cloud.githubusercontent.com/assets/22366324/23339818/ecfa566e-fc32-11e6-9ca2-6b0b828d6f6d.jpg)

**Comment by eylulakar** [comment]
Mockup screenshots: 

![1_signinregister](https://cloud.githubusercontent.com/assets/6651987/23339996/f4ef0d84-fc36-11e6-9f1a-c3c6961912dd.png)
![2_forgotpassword](https://cloud.githubusercontent.com/assets/6651987/23339997/f4f1b3ae-fc36-11e6-8828-4224ad8f6358.png)
![3_settings](https://cloud.githubusercontent.com/assets/6651987/23339998/f4f77208-fc36-11e6-8c03-06dc364f054c.png)
![4_latestcontents-mycontents](https://cloud.githubusercontent.com/assets/6651987/23339999/f4fd2360-fc36-11e6-9e66-37f050be60c7.png)
![5_createcontent](https://cloud.githubusercontent.com/assets/6651987/23340001/f4ff31b4-fc36-11e6-8ded-f5a881ce3c3f.png)
![6_contentdetail](https://cloud.githubusercontent.com/assets/6651987/23340002/f503c2ba-fc36-11e6-9435-f24017d29f09.png)
![7_contentdetailwithannotations](https://cloud.githubusercontent.com/assets/6651987/23340004/f50e62d8-fc36-11e6-87d7-2ec42e36ad19.png)
![9_myannotations](https://cloud.githubusercontent.com/assets/6651987/23340003/f50e4078-fc36-11e6-90f9-1b2a37640391.png)
![8_createannotation](https://cloud.githubusercontent.com/assets/6651987/23340005/f5192b78-fc36-11e6-8411-e5ad934c3c21.png)

**Comment by bozavci** [comment]
I have updated createdContent and ContentDetail pages as below according to the feedback we received last week.
![6_contentdetail_v2](https://cloud.githubusercontent.com/assets/22366324/23590286/9055007c-01e5-11e7-837c-35d0d475d4c1.png)
![5_createcontent_v2](https://cloud.githubusercontent.com/assets/22366324/23590285/903ca9f0-01e5-11e7-8aba-1decfd85b3c9.png)

**Comment by atabn** [comment]
I have added 2 screens: 'Create heritage category template' and 'search'.

![create category](https://cloud.githubusercontent.com/assets/17414451/23612505/b9b4291e-028c-11e7-8ff7-6250c9bacfbb.png)

![search](https://cloud.githubusercontent.com/assets/17414451/23612606/1765935e-028d-11e7-82c3-8b8bc16c87ad.png)

**Comment by ozanyarci** [comment]
Merhaba,
Mockupları güncellemek için ne yapmalıyım?
https://eylulakar574.mybalsamiq.com/projects/swe574/grid

**Comment by ozanyarci** [comment]
[LastestContents_MyContents_v2](https://eylulakar574.mybalsamiq.com/mockups/5617466.png)
[CreateContent_v3](https://eylulakar574.mybalsamiq.com/mockups/5617403.png)
[CreateDetail_v3](https://eylulakar574.mybalsamiq.com/mockups/5617407.png)
[ContentDetailWithAnnotations_v2](https://eylulakar574.mybalsamiq.com/mockups/5617805.png)
[CreateAnnotation_v2](https://eylulakar574.mybalsamiq.com/mockups/5617830.png)

**Comment by eylulakar** [comment]
Closing this.
Last version of our Mockups can be viewed via : https://eylulakar574.mybalsamiq.com/projects/swe574/grid
