### ISSUE TITLE
Backend Project structure should be created

### ISSUE THREAD

**Issue by bozavci** [SWE574-Unity/Heritage#17]

**Comment by koray-bostanci** [comment]
Working on the main backend structure and will commit it to the **development** branch as soon as possible. So that we can start backend development in parallel tasks.

**Comment by koray-bostanci** [comment]
Working on the main backend structure and will commit it to the **development** branch as soon as possible. So that we can start backend development in parallel tasks.

**Comment by koray-bostanci** [comment]
I've pushed the main project structure for the backend api. It does not contain any implementation for the requirements of the project, just a skeleton for starting the backend development. We can start with this base and improve it for our needs.

**Comment by koray-bostanci** [comment]
Closing the issue. Please re-open if you've any objection or something to discuss.
