### ISSUE TITLE
Annotation javascript libraries should be researched

### ISSUE THREAD

**Issue by bozavci** [SWE574-Unity/Heritage#19]

**Comment by ozanyarci** [comment]
Annototator.js : https://blog.idrsolutions.com/2014/01/adding-annotations-annotator-js/ 
Repo: https://github.com/openannotation/annotator
Homepage : http://annotatorjs.org/
Jquery plugin with code : Annotations jQuery Plugin
stackoverflow, some recommended plugins: 
Annotations jQuery plugin
ZURB JavaScript Annotation Plugin
jQuery Flot Annotate Plugin

Suzan Üsküdarlı's post : http://www.hongkiat.com/blog/top-web-annotation-and-markup-tools/
