### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by edipcilli** [SWE574-Unity/Heritage#21]
Project plan will be done. What kind of tool or editor could be used for making the project plan? This post will be edited with the alternative tools or editors and samples. Please add any suggestions about the issue.

Please check the Ganttpro software development project plan template. I only opened a project with a template, nothing added other than that. If we like the editor we may continue with it to make the project plan.  Please check the properties of the editor. I am sending the login information from slack.

![project_plan](https://cloud.githubusercontent.com/assets/15068127/23669245/2295cfde-036c-11e7-83c1-653800744238.png)

**Comment by koray-bostanci** [comment]
I've previous experience with **_ProjectLibre_** and I can definetely say "it sucks" :) At least, user interface is terrible.

One alternative, that I've used before, is **_[Tom's Planner](https://www.tomsplanner.com/)_**.It's an online too and has free plan for limited features. But I remember that exporting as excel or pdf was not working good. So importing the plan to our wiki can be a little annoying.

**[_Merlin_](https://projectwizards.net/en)** and **[_OmniPlan_](https://www.omnigroup.com/omniplan/)** could be alternatives, they look good but they are paid.

Most say **_MS Project_** is the best option for planning, but we know that it's also paid. If we have a chance to use MS Project, we can continue with it.

**Comment by edipcilli** [comment]
I added some parts to template. Please check. Tomorrow morning i will finish the template version.

**Comment by koray-bostanci** [comment]
We've agreed on using GanttPro for planning purposes and @edipcilli started to prepare the initial plan.
Closing the issue.
