### ISSUE TITLE
Deciding on web application interface template

### ISSUE THREAD

**Issue by eylulakar** [SWE574-Unity/Heritage#22]
For web application, which html interface template should we use? Let's gather our recommendations here in this topic. 

I recommend using the multipurpose responsive template down below. It's not free but I had purchased it and used for some applications before. It has many kinds of content pages and I think it can be possible to edit this as we'd like for our needs. 

https://themeforest.net/item/progressive-multipurpose-responsive-template/7197521
http://preview.themeforest.net/item/progressive-multipurpose-responsive-template/full_screen_preview/7197521?_ga=1.62707817.473307845.1488890240

I'm still searching for alternative ones by the way.

**Comment by bozavci** [comment]
I like this template I'm okey with using it.

**Comment by eylulakar** [comment]
I'm closing this issue, if you have any ideas please inform.
