### ISSUE TITLE
Web application Login form interface designing and backend implementation

### ISSUE THREAD

**Issue by eylulakar** [SWE574-Unity/Heritage#23]
Login form must be designed and developed. 

Form must have the following items:
- **Email :** text input as valid email address, required
- **Password :** text input formatted as password, required
- **Login :** button for logging into the system.
- **Message:** message area for displaying message text

When login button is clicked;
- Typed informations must be queried in the system and if there is a matching user record, success message must be displayed in message area and user must be logged into the system and redirected to the main page. 
- If there is no matching record, an informative error message must be displayed.

**Comment by koray-bostanci** [comment]
Implemented by @eylulakar and @bahadirozavci
