### ISSUE TITLE
Web application Registration form interface designing and backend implementation

### ISSUE THREAD

**Issue by eylulakar** [SWE574-Unity/Heritage#24]
Registration form must be designed and developed. 

Form must have the following items:
- **Full name:** text input, required
- **Email :** text input as valid email address, required, unique
- **Password :** text input formatted as password, required
- **Register:** button for registering in the system.
- **Message:** message area for displaying message text

When register button is clicked;
- Typed email value must be queried in the system and if there is a matching user record, or if an error occures during the process, an informative error message must be displayed. 
- If there is no matching email value and other fields are valid, a user record  must be created in the system and an informative success message must be displayed in message area.

**Comment by koray-bostanci** [comment]
Implemented by @eylulakar
