### ISSUE TITLE
Web application save heritage form interface designing

### ISSUE THREAD

**Issue by bozavci** [SWE574-Unity/Heritage#33]
Heritage Fields
-----------------
- [x] Title
- [x] Description
- [x] Heritage Text
- [x] Nation 
- [x] Category
- [x] Sub Category
- [x] Location Type (Country, City, Region) 
- [ ] Coordinate
- [ ] Category based Attributes (Height for buildings)
- [ ] Photo upload (Base64)

**Comment by koray-bostanci** [comment]
Continue on #47
