### ISSUE TITLE
Unit tests for basic heritage item services should be implemented

### ISSUE THREAD

**Issue by koraybostanci** [SWE574-Unity/Heritage#49]
We should implement unit tests for the following main heritage item services.

 - [x] List Heritage Item
 - [x] Create Heritage Item
 - [x] Delete Heritage Item

**Comment by edipcilli** [comment]
list heritage item some cases added:
- list all heritage items.
-list heritage items belongs to a specific user.

tomorrow i will continue to add some more cases.

**Comment by edipcilli** [comment]
some test cases added:
- finding heritage item by id.
- create heritage item.
- user test cases

**Comment by edipcilli** [comment]
- create haritege item test case modified. Now it is working properly.

**Comment by edipcilli** [comment]
all test cases that are specified implemented successfully.

**Comment by ozanyarci** [comment]
Delete Heritage Item test added
