### ISSUE TITLE
Firefox Plugin should be developed for annotations

### ISSUE THREAD

**Issue by koraybostanci** [SWE574-Unity/Heritage#52]
A Firefox Plugin should be developed in order to show annotations of a heritage item.

**Comment by koray-bostanci** [comment]
@onatbas is working on this issue. Demonstrated a prototype which is used for creating new heritage items.

**Comment by koraybostanci** [comment]
We've started to implement an plugin and showed as a demo in the class. Source code of this sample plugin is hosted in the plugin directory of the repository. But since we've incomplete features, we've agreed on not fully supporting the plugin feature. Closing this issue for now, it can be reopened if we change our  decision.
